# Architect HA package: restart-safe climate follow-up scheduler.
# Latest scheduled follow-up replaces previous pending follow-up.

input_boolean:
  architect_climate_followup_enabled:
    name: Architect Climate Follow-up Enabled

input_datetime:
  architect_climate_followup_at:
    name: Architect Climate Follow-up At
    has_date: true
    has_time: true

input_number:
  architect_climate_followup_temp:
    name: Architect Climate Follow-up Temp
    min: 16
    max: 30
    step: 0.5

input_text:
  architect_climate_followup_entity:
    name: Architect Climate Follow-up Entity
    max: 120

script:
  architect_schedule_climate_followup:
    alias: Architect Schedule Climate Follow-up
    mode: restart
    fields:
      entity_id:
        description: climate.* target entity_id
      temperature:
        description: Target temperature in C
      delay_hours:
        description: Hours from now for follow-up execution
    sequence:
      - variables:
          delay_hours_num: "{{ delay_hours | float(0) }}"
      - if:
          - condition: template
            value_template: "{{ delay_hours_num > 0 }}"
        then:
          - service: input_text.set_value
            target:
              entity_id: input_text.architect_climate_followup_entity
            data:
              value: "{{ entity_id }}"
          - service: input_number.set_value
            target:
              entity_id: input_number.architect_climate_followup_temp
            data:
              value: "{{ temperature | float }}"
          - service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.architect_climate_followup_at
            data:
              datetime: >-
                {{ (now() + timedelta(hours=delay_hours_num)).strftime('%Y-%m-%d %H:%M:%S') }}
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.architect_climate_followup_enabled

  architect_clear_climate_followup:
    alias: Architect Clear Climate Follow-up
    mode: single
    sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.architect_climate_followup_enabled
      - service: input_text.set_value
        target:
          entity_id: input_text.architect_climate_followup_entity
        data:
          value: ""

automation:
  - id: architect_execute_climate_followup
    alias: Architect Execute Climate Follow-up
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/1"
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_boolean.architect_climate_followup_enabled
        state: "on"
      - condition: template
        value_template: >-
          {{ states('input_text.architect_climate_followup_entity') | length > 0 }}
      - condition: template
        value_template: >-
          {% set due = states('input_datetime.architect_climate_followup_at') %}
          {{ due not in ['unknown', 'unavailable', ''] and now() >= as_datetime(due) }}
    action:
      - service: climate.set_temperature
        data:
          entity_id: "{{ states('input_text.architect_climate_followup_entity') }}"
          temperature: "{{ states('input_number.architect_climate_followup_temp') | float }}"
      - service: script.architect_clear_climate_followup
