from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Dict, Optional, Sequence


ROOT = Path(__file__).resolve().parents[2]
APP_HTML = ROOT / "docs" / "projects" / "kids-world-prototype.html"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8422


@dataclass(frozen=True)
class CreateDemoResponse:
    prompt: str
    scene_title: str
    scene_copy: str
    follow_ups: list[dict[str, str]]

    def as_payload(self) -> dict[str, Any]:
        return {
            "ok": True,
            "prompt": self.prompt,
            "sceneTitle": self.scene_title,
            "sceneCopy": self.scene_copy,
            "followUps": self.follow_ups,
        }


class KidsWorldDemoService:
    def create_demo(self, prompt: str) -> CreateDemoResponse:
        normalized = " ".join(prompt.split()).strip()
        if not normalized:
            normalized = "Make a rainbow dragon with a tiny castle on its back."

        lowered = normalized.lower()
        if "robot" in lowered:
            scene_title = "Robot Helper Workshop"
            scene_copy = (
                "Server3 received the create request, framed it as a gentle maker-scene, "
                "and returned structured follow-ups instead of an open chat loop."
            )
            follow_ups = [
                self._follow_up("Give the robot roller skates", "Push the scene toward playful motion."),
                self._follow_up("Add a cardboard city", "Turn one object into a buildable world."),
                self._follow_up("Explain how the robot works", "Branch from art into learning."),
                self._follow_up("Make it bedtime calm", "Apply tone and age rules without exposing policy text."),
            ]
        elif "story" in lowered or "home" in lowered:
            scene_title = "Story Lantern Journey"
            scene_copy = (
                "The create room used the backend seam to reinterpret the request as a story-first artifact "
                "that could later fan out into reading, narration, or a drawing card."
            )
            follow_ups = [
                self._follow_up("Add a kind whale helper", "Introduce another character without changing the room."),
                self._follow_up("Make it funnier", "Keep the same plot and change only the emotional tone."),
                self._follow_up("Turn it into a picture book page", "Shift output format while preserving intent."),
                self._follow_up("Make the ending sleepy", "Shape the content for time-of-day."),
            ]
        elif "moon" in lowered or "bedtime" in lowered or "calm" in lowered:
            scene_title = "Moon Garden Nest"
            scene_copy = (
                "This response was generated by the Kids World server, showing how bedtime-safe shaping "
                "can live in the backend instead of the child interface."
            )
            follow_ups = [
                self._follow_up("Add glowing fireflies", "Keep the mood soft and visual."),
                self._follow_up("Tell a tiny bedtime poem", "Reuse the same scene for language practice."),
                self._follow_up("Make the colors softer", "Adjust tone without opening a raw prompt box."),
                self._follow_up("Add a sleeping fox", "Expand the world gently."),
            ]
        else:
            scene_title = "Rainbow Dragon Meadow"
            scene_copy = (
                "The create room is now calling a real HTTP endpoint. Later that endpoint can hand off to "
                "speech-to-text, safety policy, prompt construction, and image generation on Server3."
            )
            follow_ups = [
                self._follow_up("Make it blue and add a moon", "Keep the scene and change the mood."),
                self._follow_up("Add a funny robot friend", "Turn one image into a small world."),
                self._follow_up("Tell a short story about it", "Branch from art into reading and narration."),
                self._follow_up("Make it gentler and bedtime calm", "Apply child-safe tone shaping."),
            ]
        return CreateDemoResponse(
            prompt=normalized,
            scene_title=scene_title,
            scene_copy=scene_copy,
            follow_ups=follow_ups,
        )

    @staticmethod
    def _follow_up(prompt: str, copy: str) -> dict[str, str]:
        label = prompt.split(",", 1)[0][:28].strip().rstrip(".")
        return {"label": label, "copy": copy, "prompt": prompt}


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Serve the Kids World demo app.")
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    return parser.parse_args(argv)


def _json_response(handler: BaseHTTPRequestHandler, payload: Dict[str, Any], status: int = 200) -> None:
    body = json.dumps(payload).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(body)))
    handler.end_headers()
    handler.wfile.write(body)


def _text_response(
    handler: BaseHTTPRequestHandler,
    body: bytes,
    *,
    content_type: str,
    status: int = 200,
) -> None:
    handler.send_response(status)
    handler.send_header("Content-Type", content_type)
    handler.send_header("Content-Length", str(len(body)))
    handler.end_headers()
    handler.wfile.write(body)


class KidsWorldHTTPServer(ThreadingHTTPServer):
    daemon_threads = True

    def __init__(self, server_address: tuple[str, int], service: KidsWorldDemoService):
        super().__init__(server_address, KidsWorldRequestHandler)
        self.service = service


class KidsWorldRequestHandler(BaseHTTPRequestHandler):
    server: KidsWorldHTTPServer

    def do_GET(self) -> None:  # noqa: N802
        if self.path in {"/", "/index.html"}:
            body = APP_HTML.read_bytes()
            _text_response(self, body, content_type="text/html; charset=utf-8")
            return
        if self.path == "/health":
            _json_response(self, {"ok": True, "app": "kids-world"})
            return
        _json_response(
            self,
            {"ok": False, "error": "not_found", "path": self.path},
            status=HTTPStatus.NOT_FOUND,
        )

    def do_POST(self) -> None:  # noqa: N802
        if self.path != "/api/create-demo":
            _json_response(
                self,
                {"ok": False, "error": "not_found", "path": self.path},
                status=HTTPStatus.NOT_FOUND,
            )
            return
        payload = self._read_json_body()
        prompt = str(payload.get("prompt", "")).strip()
        response = self.server.service.create_demo(prompt)
        _json_response(self, response.as_payload())

    def _read_json_body(self) -> dict[str, Any]:
        raw_length = self.headers.get("Content-Length", "0").strip() or "0"
        try:
            length = int(raw_length)
        except ValueError:
            length = 0
        body = self.rfile.read(max(length, 0))
        if not body:
            return {}
        decoded = json.loads(body.decode("utf-8"))
        if not isinstance(decoded, dict):
            raise ValueError("JSON body must be an object")
        return decoded

    def log_message(self, format: str, *args: object) -> None:  # noqa: A003
        return


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    server = KidsWorldHTTPServer((args.host, args.port), KidsWorldDemoService())
    print(f"Kids World demo serving on http://{args.host}:{args.port}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
